spring:
  application:
    name: webhook-handler
  rabbitmq:
    host: localhost

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "loggers"]

server:
  port: 8081

telegram:
  endpoint: "https://api.telegram.org"
---

spring.profiles: prod
spring:
  rabbitmq:
    host: beaver.rmq.cloudamqp.com
    username: sjcrebxq
    virtual-host: sjcrebxq
    password: ${RABBIT_PASSWORD}