spring:
  application:
    name: webhook-handler
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USERNAME}
    virtual-host: ${RABBIT_VIRTUAL_HOST}
    password: ${RABBIT_PASSWORD}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "loggers"]
server:
  port: 8081

telegram:
  endpoint: "https://api.telegram.org"